# Top level navigation
# children: left menu
# type:
#   - link: outer link type，should have "link" property which shows the outer link
#   - page: .vue single component type, will find the page file in ./pages
#   - module: module title type, not route
#   - group: group title type, not route
# demo: string|boolean, if demo is false, will not display demo, if null, will use "name" property as demo path, if string, will use the value as demo path
- type: link
  name: vue-components
  title: Vue组件
  link: //ftf.jd.com/wot-design/
- name: components
  title: 小程序
  children:
    - name: introduction
      title: 介绍
      demo: /
    - name: quickUse
      title: 快速上手
      demo: /
    - name: customTheme
      title: 自定义主题
      demo: /
    - name: typography
      title: 字体
      demo: /
    - type: page
      name: changelog
      title: 更新日志
      demo: /
    - name: commonProblems
      title: 常见问题
    - name: reward
      title: 打赏作者
    - type: module
      title: 组件
      children:
        - type: group
          title: 基础
          children:
            - name: button
              title: Button 按钮
            - name: icon
              title: Icon 图标
            - name: layout
              title: Layout 布局
            - name: popup
              title: Popup 弹出层
            - name: resize
              title: Resize 监听元素尺寸变化
            - name: transition
              title: Transition 动画
        - type: group
          title: 导航
          children:
            - name: pagination
              title: Pagination 分页
            - name: popover
              title: Popover 气泡
            - name: tabs
              title: Tabs 标签页
        - type: group
          title: 数据输入
          children:
            - name: calendar
              title: Calendar 日历选择器
            - name: calendarView
              title: CalendarView 日历面板
            - name: checkbox
              title: Checkbox 复选框
            - name: colPicker
              title: ColPicker 多列选择器
            - name: datetimePicker
              title: DatetimePicker 时间选择器
            - name: datetimePickerView
              title: DatetimePickerView 时间选择器视图
            - name: form
              title: Form 表单组合
            - name: input
              title: Input 输入框
            - name: inputNumber
              title: InputNumber 计数器
            - name: picker
              title: Picker 选择器
            - name: pickerView
              title: PickerView 选择器视图
            - name: radio
              title: Radio 单选框
            - name: rate
              title: Rate 评分
            - name: search
              title: Search 搜索框
            - name: selectPicker
              title: SelectPicker 单复选选择器
            - name: slider
              title: Slider 滑块
            - name: switch
              title: Switch 开关
            - name: upload
              title: Upload 上传
        - type: group
          title: 反馈
          children:
            - name: actionSheet
              title: ActionSheet 动作面板
            - name: dropMenu
              title: DropMenu 下拉菜单
            - name: loading
              title: Loading 加载
            - name: messageBox
              title: MessageBox 弹框
            - name: noticeBar
              title: NoticeBar 通知栏
            - name: progress
              title: Progress 进度条
            - name: sortButton
              title: SortButton 排序按钮
            - name: statusTip
              title: StatusTip 缺省提示
            - name: swipeAction
              title: SwipeAction 滑动操作
            - name: toast
              title: Toast 轻提示
            - name: tooltip
              title: Tooltip 文字提示
        - type: group
          title: 数据展示
          children:
            - name: badge
              title: Badge 角标
            - name: card
              title: Card 卡片
            - name: cell
              title: Cell 单元格
            - name: collapse
              title: Collapse 折叠面板
            - name: curtain
              title: Curtain 幕帘
            - name: divider
              title: Divider 分割线
            - name: img
              title: Img 图片
            - name: imgCropper
              title: ImgCropper 图片裁剪
            - name: grid
              title: Grid 宫格
            - name: loadmore
              title: Loadmore 加载更多
            - name: steps
              title: Steps 步骤条
            - name: sticky
              title: Sticky 粘性布局
            - name: tag
              title: Tag 标签